# Generated by Django 5.1.6 on 2025-05-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0002_page_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('background_image', models.ImageField(upload_to='slides/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
