# Generated by Django 5.1.6 on 2025-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0003_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.RemoveField(
            model_name='page',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='content',
        ),
        migrations.AddField(
            model_name='section',
            name='template_name',
            field=models.CharField(default='sections/default.html', max_length=255),
        ),
    ]
