# Generated by Django 5.1.6 on 2025-05-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0004_alter_section_options_remove_page_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='template_name',
            field=models.CharField(default='default.html', max_length=255),
        ),
    ]
