# Generated by Django 5.1.6 on 2025-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0005_section_image_alter_section_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apropos_accueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_ligne_1', models.CharField(max_length=255, verbose_name='Titre - ligne 1')),
                ('titre_ligne_2', models.CharField(max_length=255, verbose_name='Titre - ligne 2')),
                ('description', models.TextField(verbose_name="Description de l'offre")),
                ('texte_bouton', models.CharField(max_length=100, verbose_name='Texte du bouton')),
                ('lien_bouton', models.URLField(verbose_name='Lien du bouton')),
                ('image', models.ImageField(upload_to='image_Apropos_accueil/', verbose_name="Image de l'offre")),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
