# Generated by Django 5.1.6 on 2025-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0006_apropos_accueil_alter_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apropos_accueil',
            name='titre_ligne_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre - ligne 3'),
        ),
    ]
