# Generated by Django 5.1.6 on 2025-06-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0007_apropos_accueil_titre_ligne_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apropos_salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('etoiles', models.IntegerField(default=5)),
                ('logo', models.ImageField(help_text='Logo du salon de coiffure', upload_to='salons_logos/')),
                ('est_recommande', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config_Apropos_salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_principal', models.CharField(default='Les salons les plus recommandés', max_length=200)),
                ('texte_bouton_enregistrement', models.CharField(default='Inscrire un salon de coiffure', max_length=100)),
                ('url_bouton_enregistrement', models.URLField(blank=True, default='/salons/inscrire/', help_text="URL vers laquelle le bouton d'inscription redirigera (ex: /mon-app/inscription/)")),
            ],
            options={
                'verbose_name': "Configuration de la Page d'Accueil",
                'verbose_name_plural': "Configurations de la Page d'Accueil",
            },
        ),
        migrations.AlterField(
            model_name='apropos_accueil',
            name='image',
            field=models.ImageField(upload_to='image_Apropos_accueil/', verbose_name='Image'),
        ),
    ]
