# Generated by Django 5.1.6 on 2025-06-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0008_apropos_salon_config_apropos_salon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config_Apropos_salon',
        ),
        migrations.AlterModelOptions(
            name='apropos_salon',
            options={'verbose_name': 'Salon et Configuration de Page', 'verbose_name_plural': 'Salons et Configurations de Page'},
        ),
        migrations.AddField(
            model_name='apropos_salon',
            name='texte_bouton_enregistrement',
            field=models.CharField(default='Inscrire un salon de coiffure', max_length=100),
        ),
        migrations.AddField(
            model_name='apropos_salon',
            name='titre_principal',
            field=models.CharField(default='Les salons les plus recommandés', max_length=200),
        ),
        migrations.AddField(
            model_name='apropos_salon',
            name='url_bouton_enregistrement',
            field=models.URLField(blank=True, default='/salons/inscrire/', help_text="URL vers laquelle le bouton d'inscription redirigera (ex: /mon-app/inscription/)"),
        ),
    ]
