# Generated by Django 5.1.6 on 2025-06-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0009_delete_config_apropos_salon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil_salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('etoiles', models.IntegerField(default=5)),
                ('logo', models.ImageField(help_text='Logo du salon de coiffure', upload_to='salons_logos/')),
                ('est_recommande', models.BooleanField(default=True)),
                ('titre_principal', models.CharField(default='Les salons les plus recommandés', max_length=200)),
                ('texte_bouton_enregistrement', models.CharField(default='Inscrire un salon de coiffure', max_length=100)),
                ('url_bouton_enregistrement', models.URLField(blank=True, default='/salons/inscrire/', help_text="URL vers laquelle le bouton d'inscription redirigera (ex: /mon-app/inscription/)")),
            ],
            options={
                'verbose_name': 'Salon et Configuration de Page',
                'verbose_name_plural': 'Accueil_salon',
            },
        ),
        migrations.AlterModelOptions(
            name='apropos_salon',
            options={},
        ),
        migrations.RemoveField(
            model_name='apropos_salon',
            name='texte_bouton_enregistrement',
        ),
        migrations.RemoveField(
            model_name='apropos_salon',
            name='titre_principal',
        ),
        migrations.RemoveField(
            model_name='apropos_salon',
            name='url_bouton_enregistrement',
        ),
    ]
