# Generated by Django 5.1.6 on 2025-06-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0010_accueil_salon_alter_apropos_salon_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Bannière Supérieure',
                'verbose_name_plural': 'Bannières Supérieures',
            },
        ),
        migrations.CreateModel(
            name='Coiffeuse_semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='promo_images/')),
                ('bouton_texte', models.CharField(default='Savoir Plus', max_length=50)),
                ('bouton_url', models.URLField(default='#')),
            ],
            options={
                'verbose_name': 'Section Coiffeuse de la semaine',
                'verbose_name_plural': 'Sections Coiffeuses de la semaine',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
