# Generated by Django 5.1.6 on 2025-06-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0011_banniere_coiffeuse_semaine_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coiffeuse_semaine1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part1', models.CharField(default='À PROPOS', max_length=100)),
                ('title_part2', models.CharField(default='DE NOTRE STUDIO', max_length=100)),
                ('description', models.TextField(default="La danse est un art du spectacle composé de séquences de mouvements humains soigneusement sélectionnées. Ces mouvements ont une valeur esthétique et symbolique, et sont reconnus comme tels par les interprètes et les observateurs d'une culture donnée.")),
                ('button_text', models.CharField(default='NOTRE HISTOIRE', max_length=50)),
                ('image', models.ImageField(help_text="Téléchargez l'image du danseur.", upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Contenu de la Page',
                'verbose_name_plural': 'Contenus de la Page',
            },
        ),
    ]
