# Generated by Django 5.1.6 on 2025-06-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0015_temoignage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_logo', models.ImageField(blank=True, help_text='Le logo principal du site.', null=True, upload_to='footer_logos/')),
                ('social_media_logo', models.ImageField(blank=True, help_text='Le logo utilisé pour les icônes de réseaux sociaux.', null=True, upload_to='social_media_logos/')),
                ('location_name', models.CharField(default='New York', help_text='Le nom de la localisation (ex: New York).', max_length=255)),
            ],
        ),
    ]
