# Generated by Django 5.1.6 on 2025-06-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0016_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiseEnRelationAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='accueil/')),
            ],
        ),
    ]
