# Generated by Django 5.1.6 on 2025-06-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0018_coiffeuse_rendezvous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coiffeuse',
            name='image_url',
        ),
        migrations.AddField(
            model_name='coiffeuse',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de profil de la coiffeuse.', null=True, upload_to='coiffeuses/'),
        ),
    ]
