# Generated by Django 5.1.6 on 2025-06-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0019_remove_coiffeuse_image_url_coiffeuse_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners_logos/')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['name'],
            },
        ),
    ]
