# Generated by Django 5.1.6 on 2025-06-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0022_aproposstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AproposBackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(help_text='Vidéo de fond pour la section statistiques', upload_to='videos/')),
            ],
        ),
    ]
