# Generated by Django 5.1.6 on 2025-06-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0023_aproposbackgroundvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aproposbackgroundvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Vidéo de fond pour la section statistiques', null=True, upload_to='videos/'),
        ),
    ]
