# Generated by Django 5.1.6 on 2025-06-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0024_alter_aproposbackgroundvideo_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aproposbackgroundvideo',
            old_name='video_file',
            new_name='video_fond',
        ),
    ]
