# Generated by Django 5.1.6 on 2025-06-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0025_rename_video_file_aproposbackgroundvideo_video_fond'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.CharField(max_length=255)),
                ('icone', models.CharField(choices=[('fa-envelope', 'Email'), ('fa-phone', 'Téléphone'), ('fa-map-marker-alt', 'Adresse')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('date_envoye', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe_url', models.TextField(help_text='Collez ici le code iframe Google Maps')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('sous_titre', models.CharField(max_length=255)),
                ('texte_bouton', models.CharField(default='Formulaire de contact', max_length=100)),
                ('lien_bouton', models.URLField(default='#contact')),
                ('image_background', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
    ]
