# Generated by Django 5.1.6 on 2025-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0026_contactinfo_contactmessage_mapsection_teamsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapsection',
            name='iframe_url',
        ),
        migrations.AddField(
            model_name='mapsection',
            name='map_link',
            field=models.URLField(default=2, help_text='Collez ici le lien Google Maps'),
            preserve_default=False,
        ),
    ]
