# Generated by Django 5.1.6 on 2025-06-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0027_remove_mapsection_iframe_url_mapsection_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsection',
            name='map_link',
            field=models.URLField(default='https://www.google.com/maps', help_text='Collez ici le lien Google Maps', max_length=500),
        ),
    ]
