# Generated by Django 5.1.6 on 2025-06-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0028_alter_mapsection_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalerieImageComplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galerie/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='coiffeuse_semaine1',
            options={'verbose_name': 'Coiffeuse de la semaine Accueil', 'verbose_name_plural': 'Coiffeuses de la semaine Accueil'},
        ),
    ]
