# Generated by Django 5.1.6 on 2025-06-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0029_galerieimagecomplet_alter_coiffeuse_semaine1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegalerie',
            options={},
        ),
        migrations.RenameField(
            model_name='imagegalerie',
            old_name='ordre',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='imagegalerie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='imagegalerie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagegalerie',
            name='titre',
        ),
        migrations.AddField(
            model_name='imagegalerie',
            name='image_complet',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='HC_site.galerieimagecomplet'),
            preserve_default=False,
        ),
    ]
