# Generated by Django 5.1.6 on 2025-06-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0030_alter_imagegalerie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegalerie',
            options={'ordering': ['ordre']},
        ),
        migrations.RenameField(
            model_name='imagegalerie',
            old_name='order',
            new_name='ordre',
        ),
        migrations.RemoveField(
            model_name='imagegalerie',
            name='image_complet',
        ),
        migrations.AddField(
            model_name='imagegalerie',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imagegalerie',
            name='image',
            field=models.ImageField(default=2, upload_to='galerie/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagegalerie',
            name='titre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
