# Generated by Django 5.1.6 on 2025-06-15 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0032_miseenrelationaccueil_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_lastname', models.CharField(max_length=100, verbose_name='Nom')),
                ('client_firstname', models.CharField(max_length=100, verbose_name='Prénom')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_rdv', models.DateField(verbose_name='Date souhaitée')),
                ('heure_rdv', models.TimeField(verbose_name='Heure souhaitée')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaires')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HC_site.prestation')),
            ],
        ),
    ]
