# Generated by Django 5.1.6 on 2025-06-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0034_formfield_formresponse_fieldoption_fieldresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldresponse',
            name='champ',
        ),
        migrations.RemoveField(
            model_name='fieldresponse',
            name='response',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='prestation',
        ),
        migrations.DeleteModel(
            name='FieldOption',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FieldResponse',
        ),
        migrations.DeleteModel(
            name='FormResponse',
        ),
        migrations.DeleteModel(
            name='Prestation',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
