# Generated by Django 5.1.6 on 2025-06-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0035_remove_fieldresponse_champ_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={},
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='email_client',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='nom_client',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='service_souhaite',
            new_name='prenom',
        ),
        migrations.AlterUniqueTogether(
            name='rendezvous',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='prestation',
            field=models.CharField(default='Aucune prestation', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='telephone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='adresse_rdv',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='coiffeuse',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='confirme',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='message_client',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='telephone_client',
        ),
    ]
