# Generated by Django 5.1.6 on 2025-06-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC_site', '0036_alter_rendezvous_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoiffeuseFreelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('situation_matrimoniale', models.CharField(max_length=50, verbose_name='Situation matrimoniale')),
                ('a_des_enfants', models.CharField(max_length=10, verbose_name='Avez-vous des enfants ?')),
                ('nombre_enfants', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'enfants")),
                ('lieu_habitation', models.CharField(max_length=255, verbose_name="Lieu d'habitation")),
                ('telephone', models.CharField(max_length=20, verbose_name='Contact principal')),
                ('contact_urgence', models.CharField(max_length=20, verbose_name="Contact en cas d'urgence")),
                ('competences', models.TextField(verbose_name='Compétences')),
                ('disponibilites', models.CharField(max_length=255, verbose_name='Jours de disponibilité')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
        ),
    ]
